### ISSUE TITLE
Questions appear in the wrong language sometimes

### ISSUE THREAD

**Issue by farfromunique** [LemonAndroid/qanda-wikipedia#24]
(Frequency is about 1 in 40, anecdotally -- I have only seen 3, though)

![image](https://user-images.githubusercontent.com/4977323/42338884-2448c0dc-8040-11e8-9b05-d3eb6eab1683.png)

**Comment by MangoSmoothie101010** [comment]
Most of the times I notice a question being in a different language than the selected language it is because there is some passage of foreign language in the chosen language wikipedia article that was randomely selected.

**Comment by LemonAndroid** [comment]
wontfix since there are foreign langs used in english wp articles sometimes
