### ISSUE TITLE
Find multiple choice answers by calculating word2vec similarity

### ISSUE THREAD

**Issue by LemonAndroid** [LemonAndroid/qanda-wikipedia#27]

**Comment by SpaVec** [comment]
Hi, could you specify a bit more what should be done ?

**Comment by SpaVec** [comment]
Got it, I'll see what I can do.

**Comment by MangoSmoothie101010** [comment]
In addition to the glitch workspace (can be seen in the readme), there is a code.xyz workspace for the backend.

I'm not sure if code.xyz offers multiple users for the same account yet, so just hmu at manu@korfmann.info to obtain the credentials I use for logging in.

**Comment by SpaVec** [comment]
I managed to set it up using backup-stdlib.js, so if you want, I can use this and send you the updated files.

**Comment by SpaVec** [comment]
Also, should the other answers still come from the Wikipedia page or simply from the word2vec database ?

**Comment by MangoSmoothie101010** [comment]
What would you recommend? Is it possible to use both?

**Comment by MangoSmoothie101010** [comment]
Oh, I should delete backup-stdlib.js, it is outdated.

**Comment by MangoSmoothie101010** [comment]
The updated api is found in the tar.gz archives in the root of the repo.

I can integrate the changes tho, if you already built on top of backup-stdlib.s

**Comment by LemonAndroid** [comment]
@SpaVec The bounty increased by 100$ fiat.

**Comment by SpaVec** [comment]
Oh! I was having some trouble installing the necessary dependencies on stdlib.com (since they rely on c/c++). I've started working on a pure js node module to load models which should work on their service.

**Comment by LemonAndroid** [comment]
@SpaVec Do you understand this comment?

https://github.com/LemonAndroid/qanda-wikipedia/issues/28#issuecomment-412303886

**Comment by SpaVec** [comment]
Mmh, well the most popular pretrained word2vec models can get pretty big but smaller ones can be made that still contain most common words and names (I made one that is 42MB using this tool : https://github.com/dav/word2vec).
I thought the size limit on stdlib.com is around 100MB as I was told on their slack, but It seems it's actually around 55MB. I managed to upload the 42MB model, but I don't know if it will be possible to implement it for all languages though.

**Comment by LemonAndroid** [comment]
This issue is about english only.

**Comment by LemonAndroid** [comment]
Sorry for communicating that only now.

**Comment by LemonAndroid** [comment]
Have you thoought about doing the word2vec on another service like AWS? Performance is not so important to me right now, since I still can host it all on one server later.

**Comment by keithwhor** [comment]
Hey all, just letting you know we see this (at [Standard Library](https://stdlib.com/) / [Code.xyz](https://code.xyz). We can work on the in-browser memory footprint of Code.xyz to prevent crashing -- I don't have an ETA yet, we'll have to triage the issue first.

Also, @LemonAndroid, Code.xyz does support multiple users with read and / or write access to an API: https://stdlib.com/blog/share-apis

**Comment by LemonAndroid** [comment]
@SpaVec 

Your username on stdlib is spavec as well? If so, you should now be able to see and alter the qanda-api project.

**Comment by SpaVec** [comment]
It is, I have access to random-wikipedia-article, but not the whole api though it seems.

**Comment by LemonAndroid** [comment]
Oh, my bad, the correct project should now be accessible.

**Comment by SpaVec** [comment]
I updated qanda-api/dev to show similar words for answers using the word2vec-pure-js package I made. Now, it will get random words that are close to the answer as choices, and filter them with tags. If there aren't enough choices, it will fill the rest with randomly fetched words from the page as it was doing before.
Let me know what you think

**Comment by LemonAndroid** [comment]
Why is the filtering by tags still needed?

**Comment by SpaVec** [comment]
I thought I'd add it because sometimes words from different grammatical groups are chosen as answers because they are related, ex: "drink" and "carbonated"

Also I should also note that the model I uploaded is a pretty small one (7MB) that I put up for testing, since I was trying to keep code.xyz from exploding. I was surprised to see it seems to still work kind of OK.

**Comment by LemonAndroid** [comment]
Are you able to load the project up on code.xyz? I'm fetching it locally just now.

**Comment by SpaVec** [comment]
I can, but editing is very slow and memory usage goes through the roof, even though the project is <8MB
