### ISSUE TITLE
Implementing Word2Vec Similarity for generating multiple-choice answer options [$100]

### ISSUE THREAD

**Issue by LemonAndroid** [LemonAndroid/qanda-wikipedia#28]
There is an existing issue for this with a crypto bounty already, I created this issue to create a fiat bounty as well: https://github.com/LemonAndroid/qanda-wikipedia/issues/27.

The subject is the group of multiple choice options for questions on qanda-app.com.

There are 4 options, of which one is the correct one. The other 3 are computed based on the correct answer, by using random words from the wikipedia article that the question is fetched from and selecting 3 terms that at least share one word category (adjective, verb, etc). These word categories and the word tokenizer are provided by compromise nlp, a nlp npm package.

This current computation leads to questions having only one multiple choice option at times, since there's not always other words matching at least one word category of the correct answer.

Also, the multiple choice options could be improved as to make answering the question more difficult, since they could be more similar to correct questions.

That's why I thought about using the word2vec similarity and computing the answers based on that.

**Comment by wildart** [comment]
You would need to precompute w2v models for each language that you use, or get some available models, e.g. https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md. (They are huge, ~ 2GB. I doubt that you want to use them). In any case, it seems that your small app is ok without w2v functionality.

**Comment by LemonAndroid** [comment]
@wildart Why is it fine without w2v vector functionality and why does it matter that it is small?

**Comment by LemonAndroid** [comment]
@wildart 

Thanks for the link to the pretrained vectors. I would like to use them. Or is there anythign wrong with it?

The app very much needs the w2v scoring for choosing the multiple choice answers, to make them more difficult and also sensible.

Right now I'm selecting choices based on word tags in common with the correct answers. In some cases this leads to ansers where there is no other option than the correct answers and when finding other choices, they are very random.

**Comment by wildart** [comment]
Those models contain a lot of words, usually from 100k and much more words, so they take a lot of memory. Moreover, you do not want to run distance calculation every time you need to find nearest neighbors to some word - it is a performance overkill.
